package rules

import (
	"prushton.com/randochess/v2/board"
	rsf "prushton.com/randochess/v2/rules/rulesetFunctions"
)

var AllRulesets map[string]Ruleset = map[string]Ruleset{
	"Default": {
		Name:        "Default",
		Description: "Chess",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Open World": {
		Name:        "Open World",
		Description: "Chess on a 16x16 board",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     16,
		Height:    16,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Oops! All Knights!": {
		Name:        "Oops! All Knights!",
		Description: "All your pieces are now knights",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultKnight,
			board.Rook:   rsf.DefaultKnight,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultKnight,
			board.King:   rsf.DefaultKnight,
			board.Queen:  rsf.DefaultKnight,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.OopsAllKnightsInitBoard,
	},
	"PREPARE THYSELF": {
		Name:        "PREPARE THYSELF",
		Description: "Pawns can move across the board on their first move",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.PrepareThyselfPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	// "Have a plan to kill everyone you meet": {
	// 	Name:        "Have a plan to kill everyone you meet",
	// 	Description: "Bishops can only move one square per turn but dont need line of sight to take",
	// 	PieceRules: map[board.PieceType]func(board.Board, int, int) bool{
	// 		board.Pawn:   rsf.DefaultPawn,
	// 		board.Rook:   rsf.DefaultRook,
	// 		board.Knight: rsf.DefaultKnight,
	// 		board.Bishop: rsf.PlanBishop,
	// 		board.King:   rsf.DefaultKing,
	// 		board.Queen:  rsf.DefaultQueen,
	// 	},
	// 	Width:     8,
	// 	Height:    8,
	// 	Move:      rsf.DefaultMove,
	// 	GetWinner: rsf.DefaultGetWinner,
	// 	InitBoard: rsf.DefaultInitBoard,
	// },
	"Atomic Chess": {
		Name:        "Atomic Chess",
		Description: "Whenever you take a piece, both your and the enemy's piece disappear",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.AtomicChessMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Knook": {
		Name:        "Knook",
		Description: "The knight can now move like a rook",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.Knook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DefaultMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Dementia": {
		Name:        "Dementia",
		Description: "There is a random chance a piece will disappear every turn",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.DefaultPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.DefaultKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.DementiaMove,
		GetWinner: rsf.DefaultGetWinner,
		InitBoard: rsf.DefaultInitBoard,
	},
	"Checkers": {
		Name:        "Checkers",
		Description: "Its just checkers",
		PieceRules: map[board.PieceType]func(board.Board, int) ([]int, []int){
			board.Pawn:   rsf.CheckersPawn,
			board.Rook:   rsf.DefaultRook,
			board.Knight: rsf.DefaultKnight,
			board.Bishop: rsf.DefaultBishop,
			board.King:   rsf.CheckersKing,
			board.Queen:  rsf.DefaultQueen,
		},
		Width:     8,
		Height:    8,
		Move:      rsf.CheckersMove,
		GetWinner: rsf.CheckersGetWinner,
		InitBoard: rsf.CheckersInitBoard,
	},
}
